### ISSUE TITLE
AlignAfterOpenBracket: DontAlign is ignored in some cases

### ISSUE THREAD

**Issue by nielx** [owenca/haiku-format#27]
While formatting [HttpBuffer.cpp](https://git.haiku-os.org/haiku/plain/src/kits/network/libnetservices2/HttpBuffer.cpp?h=dev/netservices) with the current version, I noticed that the alignment of arguments within parenthesis seems to be broken. For example line 124 was originally:

```
    BString line(reinterpret_cast<const char*>(std::addressof(*offset)), std::distance(offset, result));
```

With 105 characters, this is too much. I expect it to be broken down as follows:
```
    BString line(reinterpret_cast<const char*>(std::addressof(*offset)),
        std::distance(offset, result));
```

While `haiku-format` turns it into:
```
    BString line(
        reinterpret_cast<const char*>(std::addressof(*offset)), std::distance(offset, result));
```

The `AlignAfterOpenBracket: DontAlign` is in the default config, which based on the [documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) seems to mean that the configuration option is ignored, and instead it uses `AlwaysBreak`. 

Is this a bug in (this version of) clang-format, or am I missing something?

**Comment by owenca** [comment]
@nielx it appears to be a bug in clang-format since version 14 or earlier. Can you file a bug report [there](https://github.com/llvm/llvm-project/issues)? Thanks!

**Comment by nielx** [comment]
> @nielx it appears to be a bug in clang-format since version 14 or earlier. Can you file a bug report [there](https://github.com/llvm/llvm-project/issues)? Thanks!

Wouldn't the solution be to uplift the clang-format version haiku-format is based on to llvm 15 instead?

**Comment by nielx** [comment]
I am offering to do this, if that's the best way forward.

**Comment by owenca** [comment]
> > @nielx it appears to be a bug in clang-format since version 14 or earlier. Can you file a bug report [there](https://github.com/llvm/llvm-project/issues)? Thanks!
> 
> Wouldn't the solution be to uplift the clang-format version haiku-format is based on to llvm 15 instead?

Actually, it was a bug _that has been fixed_ since version 14 or earlier. (We need to set `AllowAllArgumentsOnNextLine` to `false` though). So yeah, it would be better to rebase haiku-format to a current LLVM version. I think we should wait until Haiku Beta4 (and LLVM 16) is released, but please go ahead if you want to rebase to LLVM 15 before then.

**Comment by nielx** [comment]
@owenca Can we now update the embedded config to `AllowAllArgumentsOnNextLine` to be set to false?

**Comment by owenca** [comment]
I will update haiku-format to 17.0.5 as soon as clang-format of the same version is released (in about a month from now) because of some backported fixes, e.g. llvm/llvm-project#65643 and llvm/llvm-project#67892. I can turn off `AllowAllArgumentsOnNextLine` then, pending a consensus among Haiku developers. Meanwhile, you can accomplish the same with the config file. :)
